# scene
scene: igibson
scene_id: Wainscott_0_int

build_graph: true
load_texture: true
pybullet_load_texture: true
trav_map_type: no_obj
trav_map_resolution: 0.1
#0.1
trav_map_erosion: 2
should_open_all_doors: false

# domain randomization
texture_randomization_freq: null
object_randomization_freq: null

# robot setup
#robot: Fetch
#circle_size: 6 #for Fetch 
#is_discrete: false
#robot_scale: 0.85
#angular_velocity: 2.0
#linear_velocity: 1.0
#self_collision: true
#collision_ignore_link_a_ids: [0, 1, 2]  # ignore collisions with links for Fetch
#-------------------------------
robot: Locobot
robot_scale: 1.0
circle_size: 6 #for Locobot
angular_velocity: 1.0
linear_velocity: 0.5
collision_ignore_link_a_ids: [ 1, 2, 3, 4 ]  # ignore collisions with links for Locobot
self_collision: false

#Simulation details
#For one env.step() call, call 4x pybullet.step() and sync
physics_timestep: 1.0
physics_timestep_div: 120.0

action_timestep: 1.0
action_timestep_div: 10.0

mode: gui
# task setup
num_bins: 12
clip_potential_rew: false
pot_rew_clip_value: 0.2
target_dist_min: 3.0
target_dist_max: 12.0
goal_format: polar
task_obs_dim: 4
tar_objects: 6
replace_objects: false
remove_doors: true
min_episodes: 25
history_length_aux: 16
initial_aux_prob: 1.0
max_aux_episodic_prob: 0.72
resample_episode_prob: 0.15
evaluate: true
show_map: true
multiple_envs: false
resample_task: false
grid_res: 0.033
sem_categories: 6
use_aux_task: true
global_map_size: 224
#substitute polar obs-space input with previous aux pred.
substitute_polar: true
#set the distance in obs-space to zero (to neglect the one)
set_polar_dist_zero: true
#set local polar coordinates to the next geodesic distance
polar_to_geodesic: true
#not using any polar coordinates in obs-space


# reward
reward_type: geodesic
success_reward: 10.0
potential_reward_weight: 1.0
collision_reward_weight: -0.15

# discount factor
discount_factor: 0.99
# termination condition
dist_tol: 1.3  # body width
max_step: 3500
max_collisions_allowed: 600
# misc config
initial_pos_z_offset: 0.1
collision_ignore_body_b_ids: [ ] # ignore collisions with these robot links FOR LOCOBOt
#collision_ignore_link_a_ids: [6,9,2,3]  # ignore collisions with these robot links FOR HSR
#collision_ignore_body_b_ids: [2,3,1] # ignore collisions with these robot links FOR HSR
# sensor spec
output: [ task_obs, depth, seg ]
# image
# ASUS Xtion PRO LIVE
# https://www.asus.com/us/3D-Sensor/Xtion_PRO_LIVE
fisheye: false
image_width: 128
#160
image_height: 128
#120
vertical_fov: 79.0
#45.0
# depth
depth_low: 0.05
#0.005
depth_high: 5.6

# sensor noise
depth_noise_rate: 0.0
scan_noise_rate: 0.0
load_object_categories: [ shelf,door,sofa,sink,table,window ]

# visual objects
visual_object_at_initial_target_pos: true
target_visual_object_visible_to_agent: false
